### ISSUE TITLE
Bundles and @Scripts

### ISSUE THREAD

**Issue by Xiot** [WebApiContrib/WebApiContrib.Formatting.Razor#16]
Is it possible to get bundles rendered?

Adding the @Scripts.Render("~/bundles/bundlename") in the view throws the following exception
```
An exception of type 'RazorEngine.Templating.TemplateCompilationException' occurred in RazorEngine.dll but was not handled in user code

Additional information: Unable to compile template. The name 'Scripts' does not exist in the current context

Other compilation errors may have occurred. Check the Errors property for more information.
```

I tried this in the provided sample project and got the same issue.

EDIT:
I was able to get it to resolve by using a custom HtmlTemplateBase<T> and adding a Scripts property that returns a wrapper around the Scripts static class.

It appears though that the output from the Scripts.Render call is being escaped when it is being written out to the page.

**Comment by pedroreys** [comment]
:+1: @Xiot, @panesofglass can we close this issue then?

**Comment by Xiot** [comment]
Ya. If I find some time to check this out again I'll let you know
